services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:stouitou
    env_file: .env
    ports:
      - "443:443"     # for HTPPS
    volumes:
      - website:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress     # wait for wordpress to be ready
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:stouitou
    env_file: .env
    volumes:
      - website:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:stouitou
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

volumes:
  website:
    name: website
    driver: local
    driver_opts:
      type: none    # volume not created by docker (host directory)
      device: ${HOME}/data/website
      o: bind       # bind local and host directories
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/database
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

