services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    env_file: .env
    ports:
      - "443:443"     # for HTPPS
    volumes:
      - website:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress     # wait for wordpress to be ready
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    env_file: .env
    secrets:
      - mysql_admin_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - website:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    env_file: .env
    secrets:
      - mysql_admin_password
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

volumes:
  website:
    name: website
    driver: local
    driver_opts:
      type: none    # volume not created by docker (host directory)
      device: ${HOME}/data/website
      o: bind       # bind local and host directories
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/database
      o: bind

secrets:
  mysql_admin_password:
    file: ../secrets/mysql_admin_password.txt
    # external: true
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
    # external: true
  wp_user_password:
    file: ../secrets/wp_user_password.txt
    # external: true

networks:
  inception:
    name: inception
    driver: bridge

