CREATE DATABASE IF NOT EXISTS wordpress_db;
CREATE USER IF NOT EXISTS 'main_user'@'%' IDENTIFIED BY '1234';
CREATE USER IF NOT EXISTS 'stouitou'@'%' IDENTIFIED BY 'st_password';
GRANT ALL PRIVILEGES ON wordpress_db.* TO 'main_user'@'%';
FLUSH PRIVILEGES;
